platformName: Android
#模拟器
#platformVersion: 5.1.1
#deviceName: 127.0.0.1:62025

#华为mote10
platformVersion: 9
udid:

deviceName: LKX7N17B09002482

appname: weixin.apk
noReset: True
unicodeKeyboard: True
resetKeyboard: True

#appPackage: com.huawei.android.launcher
#appActivity: com.huawei.android.launcher.unihome.UniHomeLauncher
appPackage: com.tencent.mm
appActivity: com.tencent.mm.ui.LauncherUI
chromeOptions: {'androidProcess': 'com.tencent.mm:tools'}
ip: 127.0.0.1
port: 4723

environment: 叫酒开发

# TMS
appname_tms: TMS.apk
appPackage_tms: com.callme.business.test.online
appActivity_tms: callme.ui.SplashActivity


