platformName: Android
#模拟器
#platformVersion: 9
#deviceName: LKX7N17B09002482

#华为mote10
platformVersion: 9
udid:
deviceName: LKX7N17B09002482

appname: weixin.apk
noReset: True
unicodeKeyboard: True
resetKeyboard: True

appPackage: com.tencent.mm
appActivity: com.tencent.mm.ui.LauncherUI
ip: 127.0.0.1
port: 4723

environment: 酒小二