platformName: Android
platformVersion: 9
deviceName: LKX7N17B09002482
appName: weixin.app

chromeOptions: {'androidProcess': 'com.tencent.mm:tools'}
automationName: UiAutomator2

noReset: True
unicodeKeyboard: True
resetKeyboard: True
ip: 127.0.0.1
port: 4723

#  测试环境选择
environment: 酒小二
#environment: 叫酒开发

#  测试环境选择（包括app商城，微商城，小程序）
choose: 1  # 0、执行微商城。1、执行app。2、执行小程序

#appPackage: com.tencent.mm  # 酒小二微商城
#appActivity: com.tencent.mm.ui.LauncherUI  # 酒小二微商城

appPackage: com.callme.mall  # 酒小二app
appActivity: com.callme.mall.wxy.function.wellcome.SplashActivity  # 酒小二app
